In [3]:
#Matriz unidimensional 
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#Matriz bidimensional
b=np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
array=np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print (array)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
#Porque usar NumPy
#Cantidad de memoria asignda
import sys
S=range(1000)
print (sys.getsizeof(5)*len(S))


28000


In [11]:
D=np.arange(1000)
print(D.size*D.itemsize)

4000


In [12]:
#Velocidad
import time

SIZE = 1000000

L1= range(SIZE)
L2= range(SIZE)

start= time.time()
result=[(x,y) for x,y in zip(L1,L2)] #se usa for
print((time.time()-start)*1000) #Velocidad en Listas

230.21340370178223


In [14]:
A1=np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
result= A1+A2                   #solo se suma
print((time.time()-start)*1000) #Velocidad de Numpy


43.787240982055664


In [8]:
# Crear una matriz de unos - 3 filas 4 columnas
import numpy as np
unos=np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
# Crear una matriz de ceros - 3 filas 4 columnas
import numpy as np
ceros = np.zeros((3,4))
print (ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# Crear una matriz con valores aleatorios
import numpy as np
aleatorios = np.random.random((2,2))
print (aleatorios)

[[0.25062305 0.32700068]
 [0.67170592 0.97218665]]


In [11]:
# Crear una matriz vacía
import numpy as np
vacia = np.empty((3,2))
print (vacia)

[[2.22522868e-306 1.33511562e-306]
 [2.04712907e-306 8.01089061e-307]
 [2.11392033e-307 1.69117157e-306]]


In [12]:
# Crear una matriz con un solo valor
import numpy as np
full=np.full((2,2),8)
print (full)

[[8 8]
 [8 8]]


In [14]:
# Crear una matriz con valores espaciados uniformemente
import numpy as np
espaciol = np.arange(0,30,5)
print (espaciol)

[ 0  5 10 15 20 25]


In [15]:
import numpy as np
espacio2 = np.linspace(0,2,5)
print (espacio2)

[0.  0.5 1.  1.5 2. ]


In [16]:
# Crear una matriz identidad
import numpy as np
identidad1 = np.eye(4,4)
print (identidad1)

identidad2 = np.identity(4)
print (identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# Conocer las dimensiones de una matriz
import numpy as np

a= np.array([(1,2,3),(4,5,6)])
print (a.ndim)

2


In [18]:
# Conocer el tipo de los datos
print (a.dtype)

int32


In [19]:
# Conocer el tamaño y forma de la matriz
import numpy as np

a= np.array([(1,2,3,4,5,6)])
print(a.size)
print (a.shape)

6
(1, 6)


In [20]:
# Cambio de forma de una matriz
import numpy as np

a = np.array([(8,9,10),(11,12,13)]) #2 filas X 3 columnas
print (a)
a=a.reshape(3,2)#3 filas X 2 columnas
print (a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [21]:
# Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2
import numpy as np

a=np.array([(1,2,3,4),(3,4,5,6)])
print (a[0,2])

3


In [22]:
# Extraer los valores de todas las filas ubicados en la columna 3
import numpy as np

a=np.array([(1,2,3,4),(3,4,5,6)])
print (a[0:,2])

[3 5]


In [24]:
#Encontrar el mínimo, máximo y la suma
import numpy as np

a= np.array([2,45,800])
print(a.min())
print(a.max())
print (a.sum())

2
800
847


In [25]:
# Calcular la raíz cuadrada y la desviación estándar
import numpy as np

a=np.array([(1,4,81),(33,44,50,)])
print(np.sqrt(a))
print(np.std(a))

[[1.         2.         9.        ]
 [5.74456265 6.63324958 7.07106781]]
27.5121185419565


In [26]:
# Calcular la suma, resta, multiplicación y división de dos matrices
import numpy as np

x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print (x+y)
print ()
print(x-y)
print ()
print(x*y)
print ()
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]

[[0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [ 9 16 25]]

[[1. 1. 1.]
 [1. 1. 1.]]
